import {Component} from 'react';
export const HTMLPreview = ({text})=>(
    <div className="col-sm-6">
        <label>HTML Preview (read only)</label>
        {/* Content generated by converting the Markdown to HTML */}
        <div className="form-control previewPane">
            {text}
        </div>
    </div>
)